apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: knote-app
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - overlay: dev
        gitRepo: https://github.com/dinushchathurya/tekton-manifest.git
        appPath: tekton-node-app/overlays
        appBranch: HEAD
        cluster: https://kubernetes.default.svc
      - overlay: qa
        gitRepo: https://github.com/dinushchathurya/tekton-manifest.git
        appPath: tekton-node-app/overlays
        appBranch: HEAD
        cluster: https://kubernetes.default.svc
  template:
    metadata:
      name: 'knote-{{overlay}}'
    spec:
      project: test
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2
      source:
        repoURL: '{{gitRepo}}'
        targetRevision: '{{appBranch}}'
        path: '{{appPath}}/{{overlay}}'
      destination:
        server: '{{cluster}}'
        namespace: 'knote-{{overlay}}'