namePrefix: prod-
namespace: prod
bases:
  - ../../base
imageTags:
  - name: limarktest/tekton-nodejs
    newTag: f7d647247c0eaa78ad9d86fb2dd3a7b9d4891934
patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml