namePrefix: prod-
namespace: prod
bases:
  - ../../base
imageTags:
  - name: limarktest/tekton-nodejs
    newTag: a6270c14604a59fbd1c5f98aa5b6a5ad38f9e14e
patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml