namePrefix: prod-
namespace: prod
bases:
  - ../../base
imageTags:
  - name: limarktest/tekton-nodejs
    newTag: be1bd8fc8f0ae67bf100eeabc05ae664e6f6613d
patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml