namePrefix: prod-
namespace: prod
bases:
  - ../../base
imageTags:
  - name: limarktest/tekton-nodejs
    newTag: 8d6248e917a4819cce173e6322706868bf5b23fc
patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml