namePrefix: prod-
namespace: prod
bases:
  - ../../base
imageTags:
  - name: limarktest/tekton-nodejs
    newTag: fd17870e54c01b138b369e59d6612a9f324e273b
patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml