namePrefix: prod-
namespace: prod
bases:
  - ../../base
imageTags:
  - name: limarktest/tekton-nodejs
    newTag: a219a07f04d8070f1beb739faffbaabf76162f12
patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml